# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release a version and Publish to the marketplace

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 23
        cache: maven

    - name: maven-settings-action
      uses: s4u/maven-settings-action@v3.1.0
      with:
        servers: |
          [
            {
              "id": "maven-private",
              "username": "${{ secrets.NUXEO_MAVEN_USER }}",
              "password": "${{ secrets.NUXEO_MAVEN_TOKEN }}"
            }
          ]

    - name: Install OS dependencies
      run: sudo apt-get -y install ffmpeg exiftool

    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]" 
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Release with Maven
      run: mvn -B release:prepare -DpushReleaseChanges=true -Darguments="-DskipDocker=true"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy file
      run: mkdir staging && cp ${{ vars.MP_TARGET_PATH }} staging/package.zip

    - name: Upload ZIP file
      run: |
        curl -u ${{ secrets.CONNECT_USER }}:${{ secrets.CONNECT_TOKEN }} \
            -F package=@staging/package.zip \
            "https://connect.nuxeo.com/nuxeo/site/marketplace/upload?batch=true&supported=false&${{ vars.MP_OWNER }}"
        curl -u ${{ secrets.CONNECT_USER }}:${{ secrets.CONNECT_TOKEN }} \
            -F package=@staging/package.zip \
            "https://nos-preprod-connect.nuxeocloud.com/nuxeo/site/marketplace/upload?batch=true&supported=false&${{ vars.MP_OWNER }}"
